-- Migration: Create purchase_requisitions Table in Supabase
-- This table stores Procurement Request (PR) forms with multi-stage approval.

CREATE TABLE IF NOT EXISTS public.purchase_requisitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_username TEXT NOT NULL,
    requester_fullname TEXT NOT NULL,
    department TEXT NOT NULL,
    request_date DATE NOT NULL DEFAULT CURRENT_DATE,
    paid_to TEXT,
    bank_account TEXT,
    requested_items JSONB NOT NULL DEFAULT '[]', -- array of {no, description, qty}
    it_recommendations JSONB DEFAULT '[]', -- array of {no, description, qty, vendor, price}
    notes TEXT,
    grand_total NUMERIC DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Pending Supervisor', -- 'Pending Supervisor', 'Pending VP', 'Pending Finance', 'Pending Accounting', 'Approved', 'Rejected'
    
    -- Approver tracking
    supervisor_id TEXT,
    supervisor_name TEXT,
    supervisor_approved_at TIMESTAMPTZ,
    
    vp_id TEXT,
    vp_name TEXT,
    vp_approved_at TIMESTAMPTZ,
    
    finance_id TEXT,
    finance_name TEXT,
    finance_approved_at TIMESTAMPTZ,
    
    accounting_id TEXT,
    accounting_name TEXT,
    accounting_approved_at TIMESTAMPTZ,
    
    reject_reason TEXT,
    rejected_by TEXT,
    rejected_at TIMESTAMPTZ,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.purchase_requisitions ENABLE ROW LEVEL SECURITY;

-- Create Policies for Authenticated and Anonymous Users
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.purchase_requisitions;
CREATE POLICY "Allow all actions for authenticated users" 
ON public.purchase_requisitions 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all actions for anonymous users" ON public.purchase_requisitions;
CREATE POLICY "Allow all actions for anonymous users" 
ON public.purchase_requisitions 
FOR ALL 
TO anon 
USING (true)
WITH CHECK (true);
