-- Migration: Create it_asset_handovers Table in Supabase
-- This table stores all BAST Asset Handover Form records.

CREATE TABLE IF NOT EXISTS public.it_asset_handovers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT REFERENCES public.it_assets(id) ON DELETE SET NULL,
    doc_no TEXT NOT NULL,
    handover_date DATE NOT NULL,
    recipient_name TEXT NOT NULL,
    recipient_company TEXT,
    recipient_position TEXT,
    recipient_division TEXT,
    recipient_dept TEXT,
    recipient_location TEXT,
    originator_name TEXT NOT NULL,
    originator_company TEXT,
    originator_position TEXT,
    originator_dept TEXT,
    include_bag BOOLEAN DEFAULT TRUE,
    bag_serial TEXT,
    bag_remarks TEXT DEFAULT 'Black',
    include_charger BOOLEAN DEFAULT TRUE,
    charger_serial TEXT,
    charger_remarks TEXT DEFAULT 'Black',
    include_mouse BOOLEAN DEFAULT TRUE,
    mouse_model TEXT DEFAULT 'Mouse Wireless Logitech B170',
    mouse_serial TEXT,
    mouse_remarks TEXT DEFAULT 'Black',
    custom_equipments JSONB DEFAULT '[]'::jsonb,
    note TEXT,
    asset_remark TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.it_asset_handovers ENABLE ROW LEVEL SECURITY;

-- Create Policies for Authenticated and Anonymous Users
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.it_asset_handovers;
CREATE POLICY "Allow all actions for authenticated users" 
ON public.it_asset_handovers 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all actions for anonymous users" ON public.it_asset_handovers;
CREATE POLICY "Allow all actions for anonymous users" 
ON public.it_asset_handovers 
FOR ALL 
TO anon 
USING (true)
WITH CHECK (true);
