-- Migration: Create purchase_budgets Table in Supabase
-- This table stores monthly budget targets by year and category.

CREATE TABLE IF NOT EXISTS public.purchase_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    category TEXT NOT NULL,
    january NUMERIC DEFAULT 0,
    february NUMERIC DEFAULT 0,
    march NUMERIC DEFAULT 0,
    april NUMERIC DEFAULT 0,
    may NUMERIC DEFAULT 0,
    june NUMERIC DEFAULT 0,
    july NUMERIC DEFAULT 0,
    august NUMERIC DEFAULT 0,
    september NUMERIC DEFAULT 0,
    october NUMERIC DEFAULT 0,
    november NUMERIC DEFAULT 0,
    december NUMERIC DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by TEXT,
    UNIQUE (year, category)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.purchase_budgets ENABLE ROW LEVEL SECURITY;

-- Create Policies for Authenticated and Anonymous Users
DROP POLICY IF EXISTS "Allow all actions for authenticated users" ON public.purchase_budgets;
CREATE POLICY "Allow all actions for authenticated users" 
ON public.purchase_budgets 
FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all actions for anonymous users" ON public.purchase_budgets;
CREATE POLICY "Allow all actions for anonymous users" 
ON public.purchase_budgets 
FOR ALL 
TO anon 
USING (true)
WITH CHECK (true);

-- Seed initial data for Year 2026
INSERT INTO public.purchase_budgets (year, category, january, february, march, april, may, june, july, august, september, october, november, december, created_by)
VALUES 
(2026, 'Hardware', 10000000, 15000000, 2000000, 1000000, 20000000, 0, 0, 0, 0, 0, 0, 0, 'System'),
(2026, 'Accessories', 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 'System'),
(2026, 'Cloud & Hosting', 4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 'System'),
(2026, 'Subscription', 3500000, 4000000, 1000000, 1000000, 1000000, 1000000, 1000000, 1000000, 1000000, 1000000, 1000000, 1000000, 'System'),
(2026, 'Maintenance & Support', 2000000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 500000, 'System'),
(2026, 'IT Services', 15000000, 1000000, 1000000, 1000000, 2000000, 1000000, 1000000, 1000000, 1000000, 1000000, 1000000, 1000000, 'System')
ON CONFLICT (year, category) DO NOTHING;
